# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-22 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_qr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=200)),
                ('is_open', models.BooleanField()),
                ('created_on', models.DateTimeField()),
                ('last_edited', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.Attribute')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.Task')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='process_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.ProcessType'),
        ),
        migrations.AddField(
            model_name='task',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.ProductType'),
        ),
        migrations.AddField(
            model_name='item',
            name='creating_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.Task'),
        ),
        migrations.AddField(
            model_name='input',
            name='input_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.Item'),
        ),
        migrations.AddField(
            model_name='input',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.Task'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='process_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.ProcessType'),
        ),
    ]
