# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='task_id',
            new_name='task',
        ),
    ]
