# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0002_auto_20161130_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
