# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-01 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0003_auto_20161201_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='last_edited',
            new_name='updated_at',
        ),
    ]
