# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0004_auto_20161201_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('index', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='item_qr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(max_length=20),
        ),
    ]
