# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0006_auto_20161213_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LabelIndex',
        ),
    ]
