# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 23:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0009_auto_20161213_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 1, 10, 23, 22, 27, 277569, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskattribute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 1, 10, 23, 22, 34, 494778, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
