# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0013_auto_20170119_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_qr',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
