# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-19 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0014_auto_20170119_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='display',
        ),
        migrations.AlterField(
            model_name='task',
            name='label_index',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
    ]
