# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-26 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0015_auto_20170119_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_trashed',
            field=models.BooleanField(default=True),
        ),
    ]
