# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-01 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0018_auto_20170131_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtype',
            name='x',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='y',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
