# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0019_auto_20170201_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.ProcessType')),
                ('recommended_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_input', to='ics.ProcessType')),
            ],
        ),
    ]
