# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0021_processtype_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processtype',
            options={'ordering': ['x']},
        ),
    ]
