# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-03 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0022_auto_20170303_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='experiment',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='task',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
