# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-07 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0023_auto_20170303_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='processtype',
            name='output_desc',
            field=models.CharField(default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='keywords',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='unit',
            field=models.CharField(default='container', max_length=20),
        ),
    ]
