# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0025_auto_20170315_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
    ]
