# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0025_auto_20170315_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ics.User'),
            preserve_default=False,
        ),
    ]
