# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 00:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0028_auto_20170316_2213'),
    ]

    operations = [
    ]
