# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-30 18:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ics', '0029_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IT', 'in_transit'), ('RC', 'received')], default='IT', max_length=2)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('intended_destination', models.CharField(blank=True, max_length=50)),
                ('deliverable', models.BooleanField(default=False)),
                ('group_qr', models.CharField(blank=True, max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovementItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='input',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='ics.Task'),
        ),
        migrations.AlterField(
            model_name='item',
            name='creating_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ics.Task'),
        ),
        migrations.AlterField(
            model_name='taskattribute',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='ics.Task'),
        ),
        migrations.AddField(
            model_name='movementitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.Item'),
        ),
        migrations.AddField(
            model_name='movementitem',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.Movement'),
        ),
    ]
