# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-20 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0032_auto_20170410_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
