# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0035_auto_20170501_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producttype',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
