# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0036_auto_20170503_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('goal_unit', models.CharField(max_length=20)),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='ics.ProcessType')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='ics.ProductType')),
            ],
        ),
    ]
