# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0038_auto_20170612_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
