# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0039_auto_20170612_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_unit',
        ),
    ]
