# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-12 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0041_auto_20170627_1651'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=10),
        ),
    ]
