# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0042_auto_20170912_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
