# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0044_auto_20170914_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expires_at',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expires_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='token_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
