# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0045_auto_20170915_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gauth_access_token',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gauth_refresh_token',
            field=models.CharField(max_length=100),
        ),
    ]
