# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0047_auto_20170915_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='datatype',
            field=models.CharField(choices=[(b'TEXT', b'text data'), (b'NUMB', b'number data'), (b'DATE', b'date data'), (b'TIME', b'time data')], default=b'TEXT', max_length=4),
        ),
    ]
