# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0048_attribute_datatype'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
