# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0049_item_is_virtual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('a', 'admin'), ('w', 'worker')], default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='item',
            name='team_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ics.Team'),
        ),
        migrations.AddField(
            model_name='movement',
            name='team_destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='ics.Team'),
        ),
        migrations.AddField(
            model_name='movement',
            name='team_origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='ics.Team'),
        ),
        migrations.AddField(
            model_name='processtype',
            name='team_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='ics.Team'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='team_created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ics.Team'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='ics.Team'),
        ),
    ]
