# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0049_auto_20170928_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='producttype',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
