# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0050_auto_20171011_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='team_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='ics.Team'),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='team_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='ics.Team'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='team_created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ics.Team'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userprofiles', to='ics.Team'),
        ),
    ]
