# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0051_auto_20171016_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='ics.UserProfile'),
        ),
    ]
