# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0050_auto_20170928_2253'),
        ('ics', '0052_goal_userprofile'),
    ]

    operations = [
    ]
