# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0053_merge_20171019_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gauth_email',
            field=models.TextField(null=True),
        ),
    ]
