# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0054_userprofile_gauth_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='timerange',
            field=models.CharField(choices=[('d', 'day'), ('w', 'week'), ('m', 'month')], default='w', max_length=1),
        ),
    ]
