# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-26 20:16
from __future__ import unicode_literals

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0055_goal_timerange'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search'], name='ics_task_search_bdf237_gin'),
        ),
    ]
