# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0056_auto_20171026_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='readable_qr',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
