# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-03 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0057_item_readable_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='ics.Item'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
