# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 22:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0058_auto_20171103_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='ics.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=70, null=True)),
                ('shipping_addr', models.CharField(max_length=150, null=True)),
                ('billing_addr', models.CharField(max_length=150, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='ics.Account')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('price_updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_units', to='ics.ProcessType')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_units', to='ics.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('o', 'ordered'), ('p', 'processing'), ('c', 'complete')], default='o', max_length=1)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='ics.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInventoryUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, default=-1, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('inventory_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_inventory_units', to='ics.InventoryUnit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_inventory_units', to='ics.Order')),
            ],
        ),
    ]
