# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0059_account_contact_inventoryunit_order_orderinventoryunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='rank',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
