# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0059_account_contact_inventoryunit_order_orderinventoryunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ics.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ics.Order')),
            ],
        ),
        migrations.AddField(
            model_name='orderinventoryunit',
            name='amount_description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
