# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-09 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0060_auto_20171109_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=-1, max_digits=10),
        ),
    ]
