# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-14 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0062_auto_20171114_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
