# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0063_auto_20171114_2248'),
        ('ics', '0060_goal_rank'),
    ]

    operations = [
    ]
