# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0068_auto_20171211_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
