# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0069_attribute_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ig', 'incomplete goals'), ('cg', 'complete goals'), ('ai', 'anomolous inputs'), ('ft', 'recently flagged tasks'), ('ut', 'recently unflagged tasks')], max_length=2)),
                ('variable_content', models.TextField(null=True)),
                ('is_displayed', models.BooleanField(default=True)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='ics.UserProfile')),
            ],
        ),
    ]
