# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0072_auto_20171220_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
