# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0073_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='all_product_types',
            field=models.BooleanField(default=False),
        ),
    ]
