# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0074_goal_all_product_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.TextField()),
                ('comparator', models.CharField(max_length=2)),
                ('is_trashed', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.Attribute')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='ics.Attribute')),
                ('formula_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.FormulaAttribute')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFormulaAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_value', models.CharField(blank=True, max_length=50)),
                ('formula_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.FormulaAttribute')),
                ('task_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.TaskAttribute')),
            ],
        ),
    ]
