# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0076_formuladependency_is_trashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskformulaattribute',
            name='task_attribute',
        ),
        migrations.AddField(
            model_name='taskformulaattribute',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ics.Task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formuladependency',
            name='formula_attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='ics.FormulaAttribute'),
        ),
    ]
