# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0077_auto_20180111_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='walkthrough',
            field=models.IntegerField(default=0),
        ),
    ]
