# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0078_userprofile_walkthrough'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='walkthrough',
            field=models.IntegerField(default=-1),
        ),
    ]
