# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0079_auto_20180117_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_code', models.CharField(max_length=100, unique=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
