# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0081_auto_20180221_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='product_types',
            field=models.ManyToManyField(through='ics.GoalProductType', to='ics.ProductType'),
        ),
    ]
