# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 23:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0082_goal_product_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('ig', 'incomplete goals'), ('cg', 'complete goals'), ('ai', 'anomolous inputs'), ('ft', 'recently flagged tasks'), ('ut', 'recently unflagged tasks')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_displayed',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='rank',
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='formulaattribute',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='formuladependency',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='goal',
            name='timerange',
            field=models.CharField(choices=[('d', 'day'), ('w', 'week'), ('m', 'month')], db_index=True, default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='invite_code',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='invitecode',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_virtual',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='processtype',
            name='x',
            field=models.DecimalField(db_index=True, decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='flag_update_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_flagged',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_trashed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
