# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 01:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0081_auto_20180221_2019'),
        ('ics', '0083_auto_20180221_2350'),
    ]

    operations = [
    ]
