# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0088_task_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='input',
            name='creating_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='ics.Task'),
        ),
        migrations.AlterField(
            model_name='input',
            name='input_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='ics.Item'),
        ),
    ]
