# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0088_item_is_generic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='datatype',
            field=models.CharField(choices=[(b'TEXT', b'text data'), (b'NUMB', b'number data'), (b'BOOL', b'boolean data'), (b'TIME', b'time data'), (b'USER', b'user data')], default=b'TEXT', max_length=4),
        ),
    ]
