# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0089_auto_20180405_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtype',
            name='description',
        ),
    ]
