# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0090_auto_20180406_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics.Ingredient'),
        ),
    ]
