# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0091_auto_20180406_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtype',
            name='description',
        ),
    ]
