# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0092_remove_processtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
    ]
