# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0094_auto_20180411_0419'),
        ('ics', '0094_auto_20180411_1719'),
    ]

    operations = [
    ]
