# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0095_merge_20180413_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='num_flagged_ancestors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='old_is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='was_flag_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='ics.Recipe'),
        ),
        migrations.AlterField(
            model_name='taskingredient',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_ingredients', to='ics.Task'),
        ),
    ]
