# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-16 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0095_merge_20180413_1814'),
        ('ics', '0096_auto_20180413_1828'),
    ]

    operations = [
    ]
