# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0096_auto_20180413_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_trashed',
            field=models.BooleanField(default=False),
        ),
    ]
