# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-17 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0098_auto_20180417_2152'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set([('product_type', 'process_type', 'is_trashed')]),
        ),
    ]
