# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-18 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0099_auto_20180417_2156'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set([]),
        ),
    ]
