# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0103_auto_20180419_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustment',
            name='explanation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
