# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 01:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0103_auto_20180419_1829'),
        ('ics', '0097_merge_20180416_1856'),
    ]

    operations = [
    ]
