# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0103_auto_20180419_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskingredient',
            name='team_inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_ingredients', to='ics.Team'),
        ),
        migrations.AlterField(
            model_name='taskingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_ingredients', to='ics.Ingredient'),
        ),
    ]
