# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-28 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0105_auto_20180425_2041'),
        ('ics', '0105_task_recipe'),
    ]

    operations = [
    ]
