# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0108_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='ics.Team'),
        ),
    ]
