# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0110_team_time_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_recurrent',
            field=models.BooleanField(default=False),
        ),
    ]
