# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0111_merge_20180625_1850'),
        ('ics', '0110_attribute_is_recurrent'),
    ]

    operations = [
    ]
