# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0112_taskfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfile',
            name='url',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
