# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0113_taskattribute_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='category',
            field=models.CharField(choices=[('wip', 'work_in_progress'), ('fg', 'finished_goods'), ('rm', 'raw_materials')], default='wip', max_length=50),
        ),
    ]
