# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0113_auto_20180703_0018'),
        ('ics', '0113_taskattribute_created_at'),
    ]

    operations = [
    ]
