# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 22:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0114_processtype_category'),
        ('ics', '0114_merge_20180705_1741'),
    ]

    operations = [
    ]
