# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0114_processtype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
