# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import ics.models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0115_merge_20180711_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_synced_with_square_at',
            field=models.DateTimeField(default=ics.models.one_month_ago),
        ),
    ]
