# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0116_merge_20180711_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_synced_with_square_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
