# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0118_taskingredient_was_flag_changed'),
    ]

    operations = [
        migrations.RenameField(
            'taskingredient', 'was_flag_changed', 'was_amount_changed'
        ),
    ]
