# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0119_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cost_set_by_user',
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
