# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-29 23:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0120_task_cost_set_by_user'),
        ('ics', '0116_auto_20180807_2326'),
    ]

    operations = [
    ]
