# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0121_merge_20180829_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='flagged_ancestors_id_string',
            field=models.TextField(null=True),
        ),
    ]
