# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-01 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0121_merge_20180829_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('is_trashed', models.BooleanField(db_index=True, default=False)),
                ('process_types', models.ManyToManyField(blank=True, related_name='tags', to='ics.ProcessType')),
                ('product_types', models.ManyToManyField(blank=True, related_name='tags', to='ics.ProductType')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ics.Team')),
            ],
        ),
    ]
