# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-12 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0122_task_flagged_ancestors_id_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='flagged_ancestors_id_string',
            field=models.TextField(default='', null=True),
        ),
    ]
