# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-15 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0123_auto_20180912_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='num_flagged_ancestors',
        ),
    ]
