# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ics', '0122_tag'),
        ('ics', '0124_remove_task_num_flagged_ancestors'),
    ]

    operations = [
    ]
