import os
# Stitch to Polymer SKU mappings for individual teams.

square_alabama = {'254KSPKT6NID7MBRX6QYIVWX': {'polymer_process_id': 15,
                                               'polymer_product_id': 188,
                                               'square_item_id': '254KSPKT6NID7MBRX6QYIVWX',
                                               'square_name': 'Gola Rainforest, Sierra Leone 70%',
                                               'stitch_line_item_id': '1684'},
                  '7FKJY4AZRDQRREHLSWJECSNL': {'polymer_process_id': 15,
                                               'polymer_product_id': 8,
                                               'square_item_id': '7FKJY4AZRDQRREHLSWJECSNL',
                                               'square_name': 'Liberia 70%',
                                               'stitch_line_item_id': '1067'},
                  '7G662Y2EY3QEM6YMV3RDGNOQ': {'polymer_process_id': 15,
                                               'polymer_product_id': 14,
                                               'square_item_id': '7G662Y2EY3QEM6YMV3RDGNOQ',
                                               'square_name': 'Piura Blanco, Peru 70%',
                                               'stitch_line_item_id': '1297'},
                  'CIRMY5XHPTZQIQZD5JZLU64C': {'polymer_process_id': 15,
                                               'polymer_product_id': 12,
                                               'square_item_id': 'CIRMY5XHPTZQIQZD5JZLU64C',
                                               'square_name': 'Maya Mountain, Belize 70%',
                                               'stitch_line_item_id': '1538'},
                  'CPPCQUFDG7KENGLCKAJIADHD': {'polymer_process_id': 15,
                                               'polymer_product_id': 9,
                                               'square_item_id': 'CPPCQUFDG7KENGLCKAJIADHD',
                                               'square_name': 'Esmeraldas, Ecuador 70%',
                                               'stitch_line_item_id': ''},
                  'CRE4MQ4XESEV3F6I5N5O5SPO': {'polymer_process_id': 15,
                                               'polymer_product_id': 25,
                                               'square_item_id': 'CRE4MQ4XESEV3F6I5N5O5SPO',
                                               'square_name': 'PNG 70%',
                                               'stitch_line_item_id': ''},
                  'CVX7IXHGKQ3FJK6ARGQKAMOM': {'polymer_process_id': 15,
                                               'polymer_product_id': 42,
                                               'square_item_id': 'CVX7IXHGKQ3FJK6ARGQKAMOM',
                                               'square_name': 'Hacienda Azul, Costa Rica 70%',
                                               'stitch_line_item_id': '1563'},
                  'DPPLEHDCESCGQ4HV3TDG56TZ': {'polymer_process_id': 15,
                                               'polymer_product_id': 47,
                                               'square_item_id': 'DPPLEHDCESCGQ4HV3TDG56TZ',
                                               'square_name': '85% Maya Mountain, Belize',
                                               'stitch_line_item_id': '1062'},
                  'FQRPLWETX5OVSWIO7K4LTSCE': {'polymer_process_id': 15,
                                               'polymer_product_id': 7,
                                               'square_item_id': 'FQRPLWETX5OVSWIO7K4LTSCE',
                                               'square_name': 'Cahabon, Guatamala 70%',
                                               'stitch_line_item_id': ''},
                  'GHOBJZ27X2T544KMMPYI2JRW': {'polymer_process_id': 15,
                                               'polymer_product_id': 6,
                                               'square_item_id': 'GHOBJZ27X2T544KMMPYI2JRW',
                                               'square_name': 'Mantuano, Venezuela 70%',
                                               'stitch_line_item_id': '1033'},
                  'JEXBVPAC6RQP37A6NYMHWUCV': {'polymer_process_id': 15,
                                               'polymer_product_id': 9,
                                               'square_item_id': 'JEXBVPAC6RQP37A6NYMHWUCV',
                                               'square_name': '85% Costa Esmeraldas, Ecuador',
                                               'stitch_line_item_id': '1725'},
                  'KZLSXBOMPG5QIA2C7KPUXP3V': {'polymer_process_id': 15,
                                               'polymer_product_id': 2,
                                               'square_item_id': 'KZLSXBOMPG5QIA2C7KPUXP3V',
                                               'square_name': 'Camino Verde, Ecuador 70%',
                                               'stitch_line_item_id': ''},
                  'OJJYVGTQXQRQSC44W72EMC7M': {'polymer_process_id': 15,
                                               'polymer_product_id': 16,
                                               'square_item_id': 'OJJYVGTQXQRQSC44W72EMC7M',
                                               'square_name': 'Zorzal Estate, D.R. 70%',
                                               'stitch_line_item_id': '1723'},
                  'POYAFZKJXJOVG25SWFB5PBBY': {'polymer_process_id': 15,
                                               'polymer_product_id': 186,
                                               'square_item_id': 'POYAFZKJXJOVG25SWFB5PBBY',
                                               'square_name': 'Tumaco, Colombia 70%',
                                               'stitch_line_item_id': '1646'},
                  'QLV2FIUDS2BD6GFX2PFNEK4C': {'polymer_process_id': 15,
                                               'polymer_product_id': 11,
                                               'square_item_id': 'QLV2FIUDS2BD6GFX2PFNEK4C',
                                               'square_name': 'San Juan Estate Trinidad 70%',
                                               'stitch_line_item_id': '1109'},
                  'TI3JROSXYAM6VEU5LBT2KOYJ': {'polymer_process_id': 15,
                                               'polymer_product_id': 17,
                                               'square_item_id': 'TI3JROSXYAM6VEU5LBT2KOYJ',
                                               'square_name': 'Zorzal Comunitario, D.R. 70%',
                                               'stitch_line_item_id': '1467'},
                  'U47I2RTHBDH4NGIRU7OQEKPI': {'polymer_process_id': 15,
                                               'polymer_product_id': 1,
                                               'square_item_id': 'U47I2RTHBDH4NGIRU7OQEKPI',
                                               'square_name': 'Ambanja, Madagascar 70%',
                                               'stitch_line_item_id': '1140'},
                  'VWIPH2BKIUQPYPX7OWQ7FGUE': {'polymer_process_id': 15,
                                               'polymer_product_id': 975,
                                               'square_item_id': 'VWIPH2BKIUQPYPX7OWQ7FGUE',
                                               'square_name': 'Anamalai, India 70%',
                                               'stitch_line_item_id': '1704'},
                  'VXEDJO4ZBOHLOIF5G6V3CXCW': {'polymer_process_id': 15,
                                               'polymer_product_id': 2,
                                               'square_item_id': 'VXEDJO4ZBOHLOIF5G6V3CXCW',
                                               'square_name': '85% Camino Verde, Ecuador',
                                               'stitch_line_item_id': '1669'},
                  'XFAXKL24J2IOQAHD2FLOGDGN': {'polymer_process_id': 15,
                                               'polymer_product_id': 5,
                                               'square_item_id': 'XFAXKL24J2IOQAHD2FLOGDGN',
                                               'square_name': 'Kokoa Kamili, Tanzania 70%',
                                               'stitch_line_item_id': '1105'},
                  'YKMA34YIPLEYE3C46K53A65X': {'polymer_process_id': 15,
                                               'polymer_product_id': 24,
                                               'square_item_id': 'YKMA34YIPLEYE3C46K53A65X',
                                               'square_name': '100% Camino Verde, Ecuador',
                                               'stitch_line_item_id': '1585'}}

stitch_alabama = {'1033': {'polymer_process_id': 15,
                           'polymer_product_id': 6,
                           'square_item_id': 'GHOBJZ27X2T544KMMPYI2JRW',
                           'square_name': 'Mantuano, Venezuela 70%',
                           'stitch_line_item_id': '1033'},
                  '1062': {'polymer_process_id': 15,
                           'polymer_product_id': 47,
                           'square_item_id': 'DPPLEHDCESCGQ4HV3TDG56TZ',
                           'square_name': '85% Maya Mountain, Belize',
                           'stitch_line_item_id': '1062'},
                  '1067': {'polymer_process_id': 15,
                           'polymer_product_id': 8,
                           'square_item_id': '7FKJY4AZRDQRREHLSWJECSNL',
                           'square_name': 'Liberia 70%',
                           'stitch_line_item_id': '1067'},
                  '1105': {'polymer_process_id': 15,
                           'polymer_product_id': 5,
                           'square_item_id': 'XFAXKL24J2IOQAHD2FLOGDGN',
                           'square_name': 'Kokoa Kamili, Tanzania 70%',
                           'stitch_line_item_id': '1105'},
                  '1109': {'polymer_process_id': 15,
                           'polymer_product_id': 11,
                           'square_item_id': 'QLV2FIUDS2BD6GFX2PFNEK4C',
                           'square_name': 'San Juan Estate Trinidad 70%',
                           'stitch_line_item_id': '1109'},
                  '1140': {'polymer_process_id': 15,
                           'polymer_product_id': 1,
                           'square_item_id': 'U47I2RTHBDH4NGIRU7OQEKPI',
                           'square_name': 'Ambanja, Madagascar 70%',
                           'stitch_line_item_id': '1140'},
                  '1297': {'polymer_process_id': 15,
                           'polymer_product_id': 14,
                           'square_item_id': '7G662Y2EY3QEM6YMV3RDGNOQ',
                           'square_name': 'Piura Blanco, Peru 70%',
                           'stitch_line_item_id': '1297'},
                  '1467': {'polymer_process_id': 15,
                           'polymer_product_id': 17,
                           'square_item_id': 'TI3JROSXYAM6VEU5LBT2KOYJ',
                           'square_name': 'Zorzal Comunitario, D.R. 70%',
                           'stitch_line_item_id': '1467'},
                  '1538': {'polymer_process_id': 15,
                           'polymer_product_id': 12,
                           'square_item_id': 'CIRMY5XHPTZQIQZD5JZLU64C',
                           'square_name': 'Maya Mountain, Belize 70%',
                           'stitch_line_item_id': '1538'},
                  '1563': {'polymer_process_id': 15,
                           'polymer_product_id': 42,
                           'square_item_id': 'CVX7IXHGKQ3FJK6ARGQKAMOM',
                           'square_name': 'Hacienda Azul, Costa Rica 70%',
                           'stitch_line_item_id': '1563'},
                  '1585': {'polymer_process_id': 15,
                           'polymer_product_id': 24,
                           'square_item_id': 'YKMA34YIPLEYE3C46K53A65X',
                           'square_name': '100% Camino Verde, Ecuador',
                           'stitch_line_item_id': '1585'},
                  '1646': {'polymer_process_id': 15,
                           'polymer_product_id': 186,
                           'square_item_id': 'POYAFZKJXJOVG25SWFB5PBBY',
                           'square_name': 'Tumaco, Colombia 70%',
                           'stitch_line_item_id': '1646'},
                  '1669': {'polymer_process_id': 15,
                           'polymer_product_id': 2,
                           'square_item_id': 'VXEDJO4ZBOHLOIF5G6V3CXCW',
                           'square_name': '85% Camino Verde, Ecuador',
                           'stitch_line_item_id': '1669'},
                  '1684': {'polymer_process_id': 15,
                           'polymer_product_id': 188,
                           'square_item_id': '254KSPKT6NID7MBRX6QYIVWX',
                           'square_name': 'Gola Rainforest, Sierra Leone 70%',
                           'stitch_line_item_id': '1684'},
                  '1704': {'polymer_process_id': 15,
                           'polymer_product_id': 975,
                           'square_item_id': 'VWIPH2BKIUQPYPX7OWQ7FGUE',
                           'square_name': 'Anamalai, India 70%',
                           'stitch_line_item_id': '1704'},
                  '1723': {'polymer_process_id': 15,
                           'polymer_product_id': 16,
                           'square_item_id': 'OJJYVGTQXQRQSC44W72EMC7M',
                           'square_name': 'Zorzal Estate, D.R. 70%',
                           'stitch_line_item_id': '1723'},
                  '1725': {'polymer_process_id': 15,
                           'polymer_product_id': 9,
                           'square_item_id': 'JEXBVPAC6RQP37A6NYMHWUCV',
                           'square_name': '85% Costa Esmeraldas, Ecuador',
                           'stitch_line_item_id': '1725'}}

DANDELION_SQUARE_ACCESS_TOKEN = os.environ['DANDELION_SQUARE_ACCESS_TOKEN']

# EXPORTED: All Stitch to Polymer SKU mappings
sku_mappings_by_team = {
	1: {
		'polymer_team_name': 'alabama',
		'polymer_team_id': 1,
		'square': square_alabama,
		'stitch': stitch_alabama,
		'square_access_token': DANDELION_SQUARE_ACCESS_TOKEN,
	}
}
